Repository Yeogigallae/Front-End, pull requests merged in 2025-01, with the labels that each got.

#2 feat: 헤더 Props방식으로 변경
  src/components/Header/Header.styles.ts
  src/components/Header/index.tsx
Labels: 💄Design, 🔨Refactor

#3 Feature/card
  src/App.css
  src/components/Card/Card.styles.ts
  src/components/Card/CardDivider.tsx
  src/components/Card/CardImage.tsx
  src/components/Card/CardItem.tsx
  src/components/Card/CardTitle.tsx
  src/components/Card/index.tsx
  src/index.css
Labels: ✨Feature, 💄Design

#4 chore: css수정 및 디자인 시스템 적용
  src/App.tsx
  src/components/Card/Card.styles.ts
  src/components/Card/Card.tsx
  src/components/Card/index.tsx
  src/components/Header/Header.styles.ts
  src/styles/theme.ts
Labels: 💄Design, 🔨Refactor

#6 style: CardItem Content 수정
  package-lock.json
  package.json
  src/assets/icons/Back.svg
  src/assets/icons/Home.svg
  src/components/Button/Button.styles.ts
  src/components/Button/Button.tsx
  src/components/Button/IconButton.tsx
  src/components/Button/index.ts
  src/components/Card/Card.styles.ts
  src/types/button.d.ts
  src/types/svg.d.ts
  src/vite-env.d.ts
  tsconfig.node.json
  vite.config.ts
Labels: 💄Design

#5 feat: 버튼 컴포넌트 생성 & svg icon 사용
  package-lock.json
  package.json
  src/assets/icons/Back.svg
  src/assets/icons/Home.svg
  src/components/Button/Button.styles.ts
  src/components/Button/Button.tsx
  src/components/Button/IconButton.tsx
  src/components/Button/index.ts
  src/types/button.d.ts
  src/types/svg.d.ts
  src/vite-env.d.ts
  tsconfig.node.json
  vite.config.ts
Labels: ✨Feature, 💄Design, ⚙️Setting

#9 feat: course 페이지 구현
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/apis/map/index.ts
  src/apis/map/types.ts
  src/assets/icons/Marker.svg
  src/components/Card/Card.styles.ts
  src/components/Card/CardDivider.tsx
  src/components/Card/CardItem.tsx
  src/components/Map/index.tsx
  src/main.tsx
  src/pages/course/DetailPage.tsx
  src/pages/course/OverViewPage.tsx
  src/pages/course/Style.ts
  src/pages/course/_components/CourseDetailCard.tsx
  src/pages/course/_components/CourseOverviewCard.tsx
  src/pages/course/_components/CoursePlaces.tsx
  src/pages/course/_components/CourseTitle.tsx
  src/pages/course/index.tsx
  src/pages/course/layout.tsx
  src/pages/course/page.tsx
  src/pages/course/test.ts
  src/react-query/queries/queries.ts
  src/types/window.d.ts
Labels: ✨Feature, 💄Design

#12 날짜 지정&유연한 선택
  package-lock.json
  package.json
  src/App.tsx
  src/GlobalStyle.ts
  src/assets/icons/Icons.ts
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/Calendar.utils.tsx
  src/components/Calendar/CalendarDays.styles.ts
  src/components/Calendar/CalendarDays.tsx
  src/components/Calendar/CalendarHeader.styles.ts
  src/components/Calendar/CalendarHeader.tsx
  src/components/Calendar/Calender.styles.ts
  src/components/Calendar/CompleteButton.styles.ts
  src/components/Calendar/CompleteButton.tsx
  src/components/Calendar/YearMonthPicker.styles.ts
  src/components/Calendar/YearMonthPicker.tsx
  src/components/FlexibleSelect/FlexibleSelect.styles.ts
  src/components/FlexibleSelect/FlexibleSelect.tsx
  src/pages/Budget/BudgetPage/BudgetPage.tsx
  src/pages/Budget/BudgetPage/Styles.ts
  src/pages/Information/CourseSharePage/CourseSharePage.tsx
  src/pages/Information/CourseSharePage/Styles.ts
  src/pages/Information/ShareChatPage/ShareChatPage.tsx
  src/pages/Information/ShareChatPage/Styles.ts
  src/pages/Information/ShareMapPage/ShareMapPage.tsx
  src/pages/Information/ShareMapPage/Styles.ts
  src/pages/Information/SharePage/SharePage.tsx
  src/pages/Information/SharePage/Styles.ts
  src/pages/Information/ShareWritePage/ShareWritePage.tsx
  src/pages/Information/ShareWritePage/Styles.ts
  src/pages/Login/LoginPage/LoginPage.tsx
  src/pages/Login/LoginPage/Styles.ts
  src/pages/Main/MainPage/MainPage.tsx
  src/pages/Main/MainPage/Styles.ts
  src/pages/MyPage/MyFriendPage/MyFriendPage.tsx
  src/pages/MyPage/MyFriendPage/Styles.ts
  src/pages/MyPage/MyProfilePage/MyProfilePage.tsx
  src/pages/MyPage/MyProfilePage/Styles.ts
  src/pages/MyPage/RoomPage/RoomPage.tsx
  src/pages/MyPage/RoomPage/Styles.ts
  src/pages/Notice/NoticePage/NoticePage.tsx
  src/pages/Notice/NoticePage/Styles.ts
  src/pages/Scheduling/BudgetSelectPage/BudgetSelectPage.tsx
  src/pages/Scheduling/BudgetSelectPage/Styles.ts
  src/pages/Scheduling/DateSelectPage/DateSelectPage.tsx
  src/pages/Scheduling/DateSelectPage/Styles.ts
  src/pages/Scheduling/SchedulePage/SchedulePage.tsx
  src/pages/Scheduling/SchedulePage/Styles.ts
  src/pages/Splash/SplashPage/SplashPage.tsx
  src/pages/Splash/SplashPage/Styles.ts
  src/pages/Vote/VoteAgreePage/Styles.ts
  src/pages/Vote/VoteAgreePage/VoteAgreePage.tsx
  src/pages/Vote/VoteCompletePage/Styles.ts
  src/pages/Vote/VoteCompletePage/VoteCompletePage.tsx
  src/pages/Vote/VoteDatePage/Styles.ts
  src/pages/Vote/VoteDatePage/VoteDatePage.tsx
  src/pages/Vote/VoteMainPage/Styles.ts
  src/pages/Vote/VoteMainPage/VoteMainPage.tsx
  src/pages/main/page.tsx
Labels: 🐞Fix, 💄Design

#15 chore: component 폴더 위치 변경, container 삭제
  src/components/Course/CourseDetailCard.tsx
  src/components/Course/CourseOverviewCard.tsx
  src/components/Course/CoursePlaces.tsx
  src/components/Course/CourseTitle.tsx
  src/pages/course/DetailPage.tsx
  src/pages/course/OverViewPage.tsx
  src/pages/course/page.tsx
Labels: 🔨Refactor

#19 Chore : map 타입 변경
  package-lock.json
  package.json
  src/components/Map/index.tsx
  src/pages/course/DetailPage.tsx
  tsconfig.json
Labels: 🔨Refactor

#23 폰트 설정
  src/assets/Fonts/Paperlogy_Bold.ttf
  src/assets/Fonts/Paperlogy_Medium.ttf
  src/assets/Fonts/Paperlogy_Regular.ttf
  src/assets/Fonts/Paperlogy_SemiBold.ttf
  src/assets/icons/Leave.svg
  src/index.css
  src/pages/Login/LoginPage/LoginPage.tsx
  src/pages/Login/LoginPage/Styles.ts
Labels: 💄Design

#24 style: 폰트 버튼, Card 적용 & font design system 적용
  src/components/Button/Button.styles.ts
  src/components/Card/Card.styles.ts
  src/components/Header/Header.styles.ts
  src/styles/theme.ts
Labels: 💄Design

#25 refactor: 컴포넌트 분리, style 파일 분리
  src/components/Course/Course.style.ts
  src/components/Course/CourseDayButton.tsx
  src/components/Course/CourseDetailCard.tsx
  src/components/Course/CourseDetailCarousel.tsx
  src/components/Course/CourseOverviewCard.tsx
  src/components/Course/CoursePlaces.tsx
  src/components/Course/CourseShareCard.tsx
  src/components/Course/CourseTitle.tsx
  src/pages/course/DetailPage.tsx
  src/pages/course/ShareCorsePage.tsx
  src/pages/course/Style.ts
  src/pages/course/page.tsx
Labels: 🔨Refactor

#26 Styles : 수정
  src/pages/Login/LoginPage/Styles.ts
Labels: 💄Design

#32 Style: design system 값 변경
  src/components/Course/CourseShareCard.tsx
  src/contexts/HeaderContext.tsx
  src/hooks/useFunnel/useFunnel.tsx
  src/pages/course/OverViewPage.tsx
  src/pages/course/ShareCorsePage.tsx
  src/pages/course/ShareCourse/Detail/_components/DetailCard.tsx
  src/pages/course/ShareCourse/Detail/index.tsx
  src/pages/course/ShareCourse/List/_components/AddPlace.tsx
  src/pages/course/ShareCourse/List/_components/ListCard.tsx
  src/pages/course/ShareCourse/List/_components/Style.ts
  src/pages/course/ShareCourse/List/index.tsx
  src/pages/course/ShareCourse/Share/index.tsx
  src/pages/course/ShareCourse/ShareCorsePage.tsx
  src/pages/course/SharedCourse/SharedCoursePage.tsx
  src/pages/course/_components/Course.style.ts
  src/pages/course/_components/CourseDayButton.tsx
  src/pages/course/_components/CourseDetailCard.tsx
  src/pages/course/_components/CourseDetailCarousel.tsx
  src/pages/course/_components/CourseOverviewCard.tsx
  src/pages/course/_components/CoursePlaces.tsx
  src/pages/course/_components/CourseTitle.tsx
  src/pages/course/layout.tsx
  src/styles/theme.ts
Labels: 💄Design

#34 feat: override를 위한 classname 추가
  src/components/Card/CardDivider.tsx
  src/components/Card/CardImage.tsx
  src/components/Card/CardItem.tsx
  src/components/Card/CardTitle.tsx
Labels: ✨Feature

#36 feat: course 페이지
  src/App.tsx
  src/assets/icons/Chain.svg
  src/components/Layout/CourseLayout.tsx
  src/pages/course/ShareCourse/List/index.tsx
  src/pages/course/ShareCourse/Share/_components/ChatInterface.tsx
  src/pages/course/ShareCourse/Share/_components/ChatMessage.tsx
  src/pages/course/ShareCourse/Share/_components/InfoToggle.tsx
  src/pages/course/ShareCourse/Share/_components/Style.ts
  src/pages/course/ShareCourse/Share/index.tsx
  src/pages/course/ShareCourse/ShareCorsePage.tsx
  src/pages/course/SharedCourse/Detail/_components/CourseDayButton.tsx
  src/pages/course/SharedCourse/Detail/_components/CourseDetailCard.tsx
  src/pages/course/SharedCourse/Detail/_components/CourseDetailCarousel.tsx
  src/pages/course/SharedCourse/Detail/_components/CoursePlaces.tsx
  src/pages/course/SharedCourse/Detail/index.tsx
  src/pages/course/SharedCourse/Overview/_components/CourseOverviewCard.tsx
  src/pages/course/SharedCourse/Overview/index.tsx
  src/pages/course/SharedCourse/SharedCoursePage.tsx
  src/pages/course/Style.ts
  src/pages/course/_components/Course.style.ts
  src/pages/course/index.tsx
  src/pages/course/page.tsx
Labels: ✨Feature

#38 feat: Card Item label 속성 다시 생성
  src/components/Card/Card.styles.ts
  src/components/Card/CardItem.tsx
  src/pages/course/ShareCourse/Detail/_components/DetailCard.tsx
Labels: ✨Feature

#28 style : login 리팩토링
  .gitignore
  src/assets/icons/kakaoLogo.svg
  src/components/Login/KakaoButton.tsx
  src/components/Login/Styles.ts
  src/pages/Login/LoginPage/LoginPage.tsx
  src/pages/Login/LoginPage/Styles.ts
  src/styles/theme.ts
Labels: 💄Design, 🔨Refactor

#39 fix: swiper module import 에러로 인한 build 에러 해결
  package-lock.json
  package.json
  src/App.tsx
  src/pages/course/ShareCourse/ShareCorsePage.tsx
  src/pages/course/SharedCourse/SharedCoursePage.tsx
  src/pages/course/page.tsx
Labels: 🐞Fix

#41 fix: svg 파일 resolve error
  src/pages/course/ShareCourse/List/_components/ListCard.tsx
Labels: 🐞Fix, 🌏Deploy

#42 fix: svg 파일 Marker
  src/pages/course/SharedCourse/Detail/_components/CoursePlaces.tsx
  vercel.json
Labels: 🌏Deploy, ✨Feature

#45 feat: meta 타이틀, 아이콘 변경
  index.html
  public/Yeogi.svg
  public/vite.svg
Labels: ✨Feature

#47 Style: Course Place figma 디자인 반영
  src/pages/course/SharedCourse/Detail/_components/CourseDayButton.tsx
  src/pages/course/SharedCourse/Detail/_components/CoursePlaces.tsx
  src/pages/course/SharedCourse/Detail/_components/Style.ts
  src/pages/course/_components/Course.style.ts
Labels: 💄Design

#48 chore: home icon 변경
  src/assets/icons/Home.svg
Labels: 💄Design

#53 Feat: PULL_REQUEST_TEMPLATE.md 생성
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ✨Feature

#61 feat: 유저 profile 페이지 생성
  src/App.tsx
  src/components/Layout/CommonContainer.tsx
  src/components/Layout/ProfileLayout.tsx
  src/pages/MyPage/MyFriendPage/Styles.ts
  src/pages/MyPage/MyProfilePage/MyProfilePage.tsx
  src/pages/MyPage/MyProfilePage/Styles.ts
  src/pages/MyPage/MyProfilePage/_components/Profile.style.ts
  src/pages/MyPage/MyProfilePage/_components/ServiceSetting.tsx
  src/pages/MyPage/MyProfilePage/_components/UserProfile.tsx
  src/pages/course/_components/Course.style.ts
Labels: ✨Feature

#62 style: 공통 컨테이너 분리
  src/pages/MyPage/MyProfilePage/_components/Profile.style.ts
Labels: 💄Design

#55 feat: main branch to dev branch PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ✨Feature

#67 Chore: 버튼 d.ts 파일 이동
  src/components/Button/Button.styles.ts
  src/components/Button/Button.tsx
  src/components/Button/IconButton.tsx
  src/components/Button/types.ts
Labels: 🔨Refactor

#73 Feat: 알림 페이지 구현
  src/App.tsx
  src/assets/icons/Notice/BudgetNoticeIcon.svg
  src/assets/icons/Notice/CourseNoticeIcon.svg
  src/assets/icons/Notice/VoteNoticeIcon.svg
  src/components/Header/Header.styles.ts
  src/components/Layout/CommonContainer.tsx
  src/components/Layout/NoticeLayout.tsx
  src/hooks/useNotice.ts
  src/index.css
  src/pages/MyPage/MyFriendPage/MyFriendPage.tsx
  src/pages/MyPage/MyFriendPage/_components/Accordion.tsx
  src/pages/MyPage/MyFriendPage/_components/Friend.style.ts
  src/pages/MyPage/MyFriendPage/_components/FriendItem.tsx
  src/pages/Notice/NoticePage/NoticePage.tsx
  src/pages/Notice/NoticePage/Styles.ts
  src/pages/Notice/NoticePage/_components/Notice.style.ts
  src/pages/Notice/NoticePage/_components/NoticeItem.tsx
  src/pages/course/ShareCourse/ShareCorsePage.tsx
  src/pages/course/SharedCourse/Detail/_components/Style.ts
  src/pages/course/SharedCourse/Overview/_components/CourseOverviewCard.tsx
Labels: ✨Feature

#70 Feat: 친구 페이지 마크업
  src/pages/MyPage/MyFriendPage/MyFriendPage.tsx
  src/pages/MyPage/MyFriendPage/_components/Accordion.tsx
  src/pages/MyPage/MyFriendPage/_components/Friend.style.ts
  src/pages/MyPage/MyFriendPage/_components/FriendItem.tsx
Labels: ✨Feature

#74 Feat : mainpage
  src/assets/icons/Alarm.svg
  src/assets/icons/Calender2.svg
  src/assets/icons/Domestic.svg
  src/assets/icons/EditFloating.svg
  src/assets/icons/Floating.svg
  src/assets/icons/Group 489.svg
  src/assets/icons/History.png
  src/assets/icons/International.svg
  src/assets/icons/MyBtn.svg
  src/assets/icons/MyFloating.svg
  src/assets/icons/Profile.svg
  src/assets/icons/Upcoming.svg
  src/assets/icons/Voting.svg
  src/components/Layout/CourseLayout.tsx
  src/components/Login/Styles.ts
  src/pages/Main/MainPage/MainPage.tsx
  src/pages/Main/MainPage/Styles.ts
  src/pages/Main/MainPage/test.ts
  src/pages/Main/_components/FloatingButton/FloatingButton.tsx
  src/pages/Main/_components/FloatingButton/Styles.ts
  src/pages/Main/_components/Main.Styles.ts
  src/pages/Main/_components/MainSection/MainSection.Styles.ts
  src/pages/Main/_components/MainSection/MainSection.tsx
  src/pages/Main/_components/MainTop.tsx
  src/pages/Main/_components/MainTravelHistory.tsx
  src/pages/Main/_components/MainUpcomingList.tsx
  src/pages/Main/_components/MainVotingList.tsx
  src/pages/Main/_components/TravelListItem/Empty.tsx
  src/pages/Main/_components/TravelListItem/TravelListItem.Styles.ts
  src/pages/Main/_components/TravelListItem/TravelListItem.tsx
  src/pages/Main/_components/UpcomingItem/Empty.tsx
  src/pages/Main/_components/UpcomingItem/UpcomingItem.Styles.ts
  src/pages/Main/_components/UpcomingItem/UpcomingItem.tsx
  src/pages/Main/_components/VotingItem/Empty.tsx
  src/pages/Main/_components/VotingItem/VotingItem.Styles.ts
  src/pages/Main/_components/VotingItem/VotingItem.tsx
  src/pages/Main/_components/VotingItem/calculateRemainingTime.ts
  src/pages/Main/_components/VotingItem/calculateVoteGauge.ts
  src/pages/Main/_components/VotingItem/renderParticipantProfiles.tsx
  src/pages/MyPage/MyFriendPage/MyFriendPage.tsx
  src/styles/theme.ts
  src/types/window.d.ts
Labels: ✨Feature

#69 Design : Splash
  src/App.tsx
  src/assets/icons/Logo.svg
  src/pages/Splash/SplashPage/SplashPage.tsx
  src/pages/Splash/SplashPage/Styles.ts
Labels: 💄Design

#76 Fix: Course 오류 수정 모음
  src/App.tsx
  src/pages/course/CoursePage.tsx
  src/pages/course/ShareCourse/List/_components/Style.ts
Labels: 🐞Fix

#83 Fix: mypage/friend 수정
  src/App.tsx
  src/pages/MyPage/MyFriendPage/_components/Accordion.tsx
  src/pages/MyPage/MyFriendPage/_components/Friend.style.ts
  src/pages/MyPage/MyFriendPage/_components/FriendItem.tsx
Labels: 🐞Fix

#90 Rename CoursePage.tsx to CoursePage.tsx
  src/pages/Course/CoursePage.tsx
  src/pages/Course/ShareCourse/Detail/_components/DetailCard.tsx
  src/pages/Course/ShareCourse/Detail/index.tsx
  src/pages/Course/ShareCourse/List/_components/AddPlace.tsx
  src/pages/Course/ShareCourse/List/_components/ListCard.tsx
  src/pages/Course/ShareCourse/List/_components/Style.ts
  src/pages/Course/ShareCourse/List/index.tsx
  src/pages/Course/ShareCourse/Share/_components/ChatInterface.tsx
  src/pages/Course/ShareCourse/Share/_components/ChatMessage.tsx
  src/pages/Course/ShareCourse/Share/_components/InfoToggle.tsx
  src/pages/Course/ShareCourse/Share/_components/Style.ts
  src/pages/Course/ShareCourse/Share/index.tsx
  src/pages/Course/ShareCourse/ShareCorsePage.tsx
  src/pages/Course/SharedCourse/Detail/_components/CourseDayButton.tsx
  src/pages/Course/SharedCourse/Detail/_components/CourseDetailCard.tsx
  src/pages/Course/SharedCourse/Detail/_components/CourseDetailCarousel.tsx
  src/pages/Course/SharedCourse/Detail/_components/CoursePlaces.tsx
  src/pages/Course/SharedCourse/Detail/_components/Style.ts
  src/pages/Course/SharedCourse/Detail/index.tsx
  src/pages/Course/SharedCourse/Overview/_components/CourseOverviewCard.tsx
  src/pages/Course/SharedCourse/Overview/index.tsx
  src/pages/Course/SharedCourse/SharedCoursePage.tsx
  src/pages/Course/_components/Course.style.ts
  src/pages/Course/_components/CourseTitle.tsx
  src/pages/Course/test.ts
Labels: 🌏Deploy

#88 Fix: 삭제된 파일 추가
  src/App.tsx
  src/assets/icons/Notice/BudgetNoticeIcon.svg
  src/assets/icons/Notice/CourseNoticeIcon.svg
  src/assets/icons/Notice/VoteNoticeIcon.svg
  src/components/Header/Header.styles.ts
  src/components/Layout/CommonContainer.tsx
  src/components/Layout/NoticeLayout.tsx
  src/hooks/useNotice.ts
  src/index.css
  src/pages/Course/ShareCourse/ShareCorsePage.tsx
  src/pages/Course/SharedCourse/Overview/_components/CourseOverviewCard.tsx
  src/pages/Notice/NoticePage/NoticePage.tsx
  src/pages/Notice/NoticePage/Styles.ts
  src/pages/Notice/NoticePage/_components/Notice.style.ts
  src/pages/Notice/NoticePage/_components/NoticeItem.tsx
Labels: 🐞Fix

#96 Feat: header center content 수정 기능 추가
  src/components/Header/HeaderCenterContent.tsx
  src/components/Header/index.tsx
  src/components/Layout/CourseLayout.tsx
  src/components/Layout/NoticeLayout.tsx
  src/components/Layout/ProfileLayout.tsx
  src/contexts/HeaderContext.tsx
  src/pages/Course/CoursePage.tsx
  src/pages/Course/ShareCourse/ShareCorsePage.tsx
  src/pages/Course/SharedCourse/SharedCoursePage.tsx
  src/pages/MyPage/MyFriendPage/MyFriendPage.tsx
  src/pages/MyPage/MyProfilePage/MyProfilePage.tsx
  src/pages/Notice/NoticePage/NoticePage.tsx
  src/types/header/header.ts
Labels: ✨Feature

#82 Style: VotePage
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/CalendarDays.styles.ts
  src/components/Calendar/CalendarDays.tsx
  src/components/Calendar/CalendarHeader.styles.ts
  src/components/Calendar/CalendarHeader.tsx
  src/components/Calendar/CalendarTabs.styles.ts
  src/components/Calendar/CalendarTabs.tsx
  src/components/Calendar/Calender.styles.ts
  src/components/Calendar/CompleteButton.tsx
  src/components/Calendar/MonthNavigation.tsx
  src/components/Calendar/YearMonthPicker.tsx
  src/components/Calendar/types/types.ts
  src/pages/Vote/ConfirmPage/ConfirmFailPage/ConfirmFailPage.tsx
  src/pages/Vote/ConfirmPage/ConfirmFailPage/Styles.ts
  src/pages/Vote/ConfirmPage/ConfirmSuccessPage/ConfirmSuccessPage.tsx
  src/pages/Vote/ConfirmPage/ConfirmSuccessPage/Styles.ts
  src/pages/Vote/ConfirmPage/_components/ConfirmFailCard/ConfirmFailCard.tsx
  src/pages/Vote/ConfirmPage/_components/ConfirmFailCard/ConfirmMessage.tsx
  src/pages/Vote/ConfirmPage/_components/ConfirmFailCard/Styles.ts
  src/pages/Vote/ConfirmPage/_components/ConfirmSuccessCard/ConfirmSuccessCard.tsx
  src/pages/Vote/ConfirmPage/_components/ConfirmSuccessCard/Styles.ts
  src/pages/Vote/ConfirmPage/_components/Recommend/Recommend.tsx
  src/pages/Vote/ConfirmPage/_components/Recommend/Styles.ts
  src/pages/Vote/ConfirmPage/_components/SuccessText.styles.ts
  src/pages/Vote/ConfirmPage/_components/SuccessText.tsx
  src/pages/Vote/VoteCard/_components/VoteCard.tsx
  src/pages/Vote/VotePage.tsx
  src/pages/Vote/VoteResult/_components/DurationInfo.tsx
  src/pages/Vote/VoteResult/_components/ResultCard.tsx
  src/pages/Vote/VoteResult/_components/VoteComponent.styles.ts
  src/pages/Vote/VoteResult/_components/VoteComponent.tsx
  src/pages/Vote/VoteResult/_components/VoteContent.tsx
  src/pages/Vote/_components/Vote.styles.ts
Labels: 💄Design, 🔨Refactor

#97 Refactor/functional
  src/apis/searchAddress/index.ts
  src/apis/searchAddress/searchPlace/index.ts
  src/apis/searchAddress/searchZip/index.ts
  src/hooks/useResultSelection.ts
  src/hooks/useSearchLogic.ts
  src/pages/Functional/CreateCalendar/CreateCalendar.tsx
  src/pages/Functional/CreateCalendar/Styles.ts
  src/pages/Functional/CreateCalendar/_components/CreateCalendar.tsx
  src/pages/Functional/CreateCalendar/index.tsx
  src/pages/Functional/CreateVote/_components/SlideContainer/SlideContainer.tsx
  src/pages/Functional/CreateVote/_components/Tabs/Tabs.tsx
  src/pages/Functional/CreateVote/_components/VoteForm/ImagePlaceholder.tsx
  src/pages/Functional/CreateVote/_components/VoteForm/MessageInput.tsx
  src/pages/Functional/CreateVote/_components/VoteForm/VoteTimes.tsx
  src/pages/Functional/FunctionalPage.tsx
  src/pages/Functional/SearchPage/SearchPage.tsx
  src/pages/Functional/SearchPage/Styles.ts
  src/pages/Functional/SearchPage/_components/ResultList.tsx
  src/pages/Functional/SearchPage/_components/SearchMap/SearchMap.tsx
  src/pages/Functional/_components/Functional.styles.ts
  src/pages/SearchPage/SearchPage.tsx
  src/pages/SearchPage/Styles.ts
  src/pages/SearchPage/_components/Pagination.styles.ts
  src/pages/SearchPage/_components/Pagination.tsx
  src/pages/SearchPage/_components/ResultList.styles.ts
  src/pages/SearchPage/_components/ResultList.tsx
  src/pages/SearchPage/_components/SearchInput.styles.ts
  src/pages/SearchPage/_components/SearchInput.tsx
  src/pages/SearchPage/_components/SearchMap/SearchMap.style.ts
  src/pages/SearchPage/_components/SearchMap/SearchMap.tsx
  src/pages/SearchPage/index.tsx
Labels: ✨Feature, 💄Design, 🔨Refactor

#104 Feat: Input 공통 컴포넌트로 분리
  src/components/Input/Input.style.ts
  src/components/Input/index.tsx
Labels: ✨Feature

#107 style:예산 정하기 페이지
  src/App.tsx
  src/assets/icons/MoneyBag.svg
  src/components/Layout/BudgetLayout.tsx
  src/pages/Budget/BudgetPage/BudgetPage.tsx
  src/pages/Budget/BudgetPage/Styles.ts
  src/pages/Budget/_components/BudgetCard.tsx
  src/pages/Budget/_components/Styles.ts
  src/pages/Budget/test.ts
Labels: 💄Design, 🔨Refactor

#116 style: Skeleton 추가
  src/components/Skeleton/Skeleton.styles.ts
  src/components/Skeleton/index.tsx
Labels: 💄Design

#114 Style: 예산 정보 카드 추가
  src/pages/Budget/BudgetPage/BudgetPage.tsx
  src/pages/Budget/BudgetPage/Styles.ts
  src/pages/Budget/_components/BudgetCard.tsx
  src/pages/Budget/_components/BudgetInfoCard.tsx
  src/pages/Budget/_components/Styles.ts
  src/pages/Budget/test.ts
Labels: 💄Design

#106 Feat: component-modal-frame
  src/assets/icons/building1.svg
  src/assets/icons/building2.svg
  src/assets/icons/building3.svg
  src/assets/icons/building4.svg
  src/assets/icons/nature1.svg
  src/assets/icons/nature2.svg
  src/assets/icons/nature3.svg
  src/assets/icons/nature4.svg
  src/components/Layout/FunctionalLayout.tsx
  src/components/Modal/ConfirmModal.tsx
  src/components/Modal/ImageModal.tsx
  src/components/Modal/Modal.styles.ts
  src/components/Modal/imageData.ts
  src/components/Modal/index.tsx
  src/pages/Functional/CreateVote/_components/SlideContainer/SlideContainer.tsx
  src/pages/Functional/CreateVote/_components/SlideContainer/Styles.ts
  src/pages/Functional/CreateVote/_components/Tabs/Tabs.styles.ts
  src/pages/Functional/CreateVote/_components/Tabs/Tabs.tsx
  src/pages/Functional/CreateVote/_components/VoteForm/ImagePlaceholder.tsx
  src/pages/Functional/CreateVote/_components/VoteForm/VoteForm.tsx
  src/pages/Functional/_components/Functional.styles.ts
  src/pages/SearchPage/_components/Pagination.tsx
  src/pages/SearchPage/_components/ResultList.tsx
  src/pages/SearchPage/_components/SearchInput.tsx
  src/pages/SearchPage/_components/SearchMap/SearchMap.style.ts
  src/pages/SearchPage/_components/SearchMap/SearchMap.tsx
  src/pages/SearchPage/types/types.ts
  src/pages/Vote/ConfirmPage/_components/Recommend/Recommend.tsx
  src/pages/Vote/ConfirmPage/_components/SuccessText.tsx
  src/pages/Vote/Travel/_components/TravelCard.tsx
  src/pages/Vote/VoteCard/_components/VoteCard.tsx
  src/pages/Vote/VoteResult/_components/ResultCard.tsx
  src/pages/Vote/_components/Vote.styles.ts
Labels: ✨Feature, 💄Design
