Repository Yeogigallae/Front-End, pull requests merged in 2025-02, with the labels that each got.

#118 Feat: useFunnel 타입 안정성 & 상태 관리 추가
  src/hooks/useFunnel/Funnel.tsx
  src/hooks/useFunnel/types.ts
  src/hooks/useFunnel/useFunnel.tsx
Labels: 🔨Refactor

#122 Style: Course Card Skeleton 생성
  src/pages/Course/CoursePage.tsx
  src/pages/Course/_components/CourseOverviewCardSkeleton.tsx
Labels: 💄Design

#123 Feat: 방 생성 페이지 친구 불러오기 기능
  src/apis/friend/index.ts
  src/apis/friend/mocks.ts
  src/apis/room/index.ts
  src/apis/room/types.ts
  src/pages/MyPage/RoomPage/RoomPageContent.tsx
  src/pages/MyPage/RoomPage/_components/MyFriend/MyFriend.tsx
  src/pages/MyPage/RoomPage/_components/MyFriend/MyFriendListItem.tsx
  src/pages/MyPage/RoomPage/_components/MyFriend/MyFriendListItemSkeleton.tsx
  src/pages/MyPage/RoomPage/_components/MyFriend/MyFriendSkeleton.tsx
  src/pages/MyPage/RoomPage/_components/MyFriend/index.ts
  src/pages/MyPage/RoomPage/_components/Room.style.ts
  src/pages/MyPage/RoomPage/_components/RoomFriend/RoomFriend.tsx
  src/pages/MyPage/RoomPage/_components/RoomFriend/RoomFriendListAvatar.tsx
  src/pages/MyPage/RoomPage/_components/RoomFriend/index.ts
  src/pages/MyPage/RoomPage/_components/RoomTitleForm/RoomTitleForm.tsx
  src/pages/MyPage/RoomPage/_components/RoomTitleForm/index.ts
  src/react-query/queries/friend/queries.ts
Labels: ✨Feature

#50 feat : 로그인 토큰 저장
  package-lock.json
  src/App.tsx
  src/apis/Login/api.ts
  src/pages/Login/Kakao.tsx
  src/pages/Login/LoginPage/LoginPage.tsx
  src/pages/Login/_components/KakaoButton.tsx
  src/pages/Login/_components/Styles.ts
  src/pages/Login/useAuthStore.ts
  src/pages/Login/withAuth.tsx
  src/pages/Main/_components/Main.Styles.ts
Labels: ✨Feature

#128 Feat: 내친구, 방 페이지 api 연결
  src/apis/friend/index.ts
  src/apis/friend/mocks.ts
  src/apis/friend/types.ts
  src/apis/room/index.ts
  src/apis/room/mocks.ts
  src/apis/room/types.ts
  src/pages/Course/CoursePage.tsx
  src/pages/MyPage/MyFriendPage/MyFriendPage.tsx
  src/pages/MyPage/MyFriendPage/_components/Accordion.tsx
  src/pages/MyPage/MyFriendPage/_components/Friend/index.tsx
  src/pages/MyPage/MyFriendPage/_components/FriendItem.tsx
  src/pages/MyPage/MyFriendPage/_components/ProfileGroup.tsx
  src/pages/MyPage/MyFriendPage/_components/Room/index.tsx
  src/pages/MyPage/MyFriendPage/_components/Skeleton.tsx
  src/pages/MyPage/RoomPage/RoomPageContent.tsx
  src/react-query/mutation/room/mutation.ts
  src/react-query/queries/room/queries.ts
Labels: ✨Feature

#129 Fix/funnel vote functional
  src/components/Layout/FunctionalLayout.tsx
  src/pages/Functional/FunctionalPage.tsx
  src/pages/Vote/VotePage.tsx
Labels: 🐞Fix

#132 Feat: Modal Component 구현
  src/components/Card/Card.tsx
  src/components/Layout/CommonContainer.tsx
  src/components/Modal/ConfirmModal.tsx
  src/components/Modal/ImageLoader.tsx
  src/components/Modal/ImageModal.tsx
  src/components/Modal/Modal.styles.ts
  src/components/Modal/core.tsx
  src/components/Modal/imageData.ts
  src/components/Modal/index.ts
  src/components/Modal/index.tsx
  src/store/modal/index.ts
Labels: ✨Feature

#133 Refactor: course page migrate
  src/pages/Course/ShareCourse/Detail/index.tsx
  src/pages/Course/ShareCourse/List/_components/ListCard.tsx
  src/pages/Course/ShareCourse/List/index.tsx
  src/pages/Course/ShareCourse/Share/index.tsx
  src/pages/Course/ShareCourse/ShareCorsePage.tsx
  src/pages/Course/SharedCourse/Detail/_components/CourseDayButton.tsx
  src/pages/Course/SharedCourse/Detail/_components/CourseDetailCarousel.tsx
  src/pages/Course/SharedCourse/Detail/_components/Style.ts
  src/pages/Course/SharedCourse/Detail/index.tsx
  src/pages/Course/SharedCourse/Overview/_components/CourseOverviewCard.tsx
  src/pages/Course/SharedCourse/Overview/index.tsx
  src/pages/Course/SharedCourse/SharedCoursePage.tsx
Labels: 🔨Refactor

#134 Fix: 방 생성 페이지 schema 변경에 따른 수정
  src/contexts/FriendContext.tsx
  src/pages/MyPage/RoomPage/RoomPageContent.tsx
  src/pages/MyPage/RoomPage/_components/MyFriend/MyFriend.tsx
  src/pages/MyPage/RoomPage/_components/RoomFriend/RoomFriend.tsx
  src/pages/MyPage/RoomPage/schema.ts
Labels: 🐞Fix

#135 Feat: 알림 페이지 API 연결
  src/apis/notice/index.ts
  src/apis/notice/mocks.ts
  src/apis/notice/types.ts
  src/hooks/useNotice.ts
  src/pages/Notice/NoticePage/NoticePage.tsx
  src/pages/Notice/NoticePage/_components/NoticeItem.tsx
  src/pages/Notice/NoticePage/_components/Skeleton.tsx
  src/react-query/queries/notice/queries.ts
Labels: 📬API

#137 chore/votePage
  src/pages/Vote/ConfirmPage/ConfirmFailPage/ConfirmFailPage.tsx
  src/pages/Vote/ConfirmPage/_components/Recommend/Recommend.tsx
  src/pages/Vote/VoteDate/_components/VoteDate.tsx
  src/pages/Vote/VoteDate/index.tsx
  src/pages/Vote/VotePage.tsx
  src/pages/Vote/VoteResult/_components/ResultCard.tsx
  src/pages/Vote/VoteResult/_components/VoteResult.tsx
  src/pages/Vote/_components/Vote.styles.ts
Labels: 🔨Refactor

#140 feat/functional-imageModal
  src/pages/Functional/CreateVote/_components/CreateVote.tsx
  src/pages/Functional/CreateVote/_components/VoteForm/Image.styles.ts
  src/pages/Functional/CreateVote/_components/VoteForm/ImagePlaceholder.tsx
  src/pages/Functional/FunctionalPage.tsx
Labels: ✨Feature, 🔨Refactor

#136 Style:mainpage 추가 화면
  src/App.tsx
  src/assets/icons/SeeMore.svg
  src/assets/icons/Vector.svg
  src/assets/icons/budget.svg
  src/assets/icons/calendar3.svg
  src/assets/icons/course.svg
  src/assets/icons/filter.svg
  src/assets/icons/trip_plan.svg
  src/assets/icons/usergroup.svg
  src/assets/icons/xBtn.svg
  src/components/Layout/FullVotingListLayout.tsx
  src/pages/Main/FullVotingListPage/FullVotingListPage.tsx
  src/pages/Main/FullVotingListPage/Styles.ts
  src/pages/Main/MainPage/test.ts
  src/pages/Main/_components/FloatingButton/FloatingButton.tsx
  src/pages/Main/_components/Main.Styles.ts
  src/pages/Main/_components/MainVotingList.tsx
  src/pages/Main/_components/TostModal/Styles.ts
  src/pages/Main/_components/TostModal/TostModal.tsx
  src/pages/Main/_components/VotingItem/FullVotingItem.tsx
  src/pages/Main/_components/VotingItem/VotingItem.Styles.ts
Labels: 💄Design

#145 fix: 방 페이지 취소 버튼 로직 추가
  src/pages/MyPage/RoomPage/RoomPageContent.tsx
Labels: 🐞Fix

#146 Refactor: SearchPage 리팩토링
  src/App.tsx
  src/apis/searchAddress/index.ts
  src/apis/searchAddress/searchPlace/index.ts
  src/apis/searchAddress/searchZip/index.ts
  src/hooks/useSearchLogic.ts
  src/pages/SearchPage/SearchPage.tsx
  src/pages/SearchPage/_components/ResultList.styles.ts
  src/pages/SearchPage/_components/ResultList.tsx
  src/pages/SearchPage/_components/SearchInput.styles.ts
  src/pages/SearchPage/_components/SearchInput.tsx
  src/pages/SearchPage/_components/SearchListItem.tsx
  src/pages/SearchPage/_components/SearchSkeleton.tsx
  src/pages/SearchPage/index.tsx
  src/pages/SearchPage/types/types.ts
  src/react-query/queries/search/queries.ts
Labels: 🔨Refactor

#117 Feat/vote apis
  src/apis/vote/mocks/tripInfoMocks.ts
  src/apis/vote/mocks/voteMocks.ts
  src/apis/vote/mocks/voteResultMocks.ts
  src/apis/vote/tripInfo.ts
  src/apis/vote/vote.ts
  src/apis/vote/voteResult.ts
  src/components/Calendar/Calendar.tsx
  src/components/Layout/VoteLayout.tsx
  src/hooks/useTripInfo.ts
  src/hooks/useVoteContext.ts
  src/pages/Main/_components/FloatingButton/FloatingButton.tsx
  src/pages/Vote/ConfirmPage/ConfirmFailPage/ConfirmFailPage.tsx
  src/pages/Vote/ConfirmPage/ConfirmSuccessPage/ConfirmSuccessPage.tsx
  src/pages/Vote/Travel/_components/TravelCard.tsx
  src/pages/Vote/VoteCard/_components/VoteCard.tsx
  src/pages/Vote/VotePage.tsx
  src/pages/Vote/VoteResult/_components/DurationInfo.tsx
  src/pages/Vote/VoteResult/_components/ResultCard.tsx
  src/pages/Vote/VoteResult/_components/VoteComponent.tsx
  src/pages/Vote/VoteResult/_components/VoteContent.tsx
  src/pages/Vote/VoteResult/_components/VoteResult.tsx
  src/pages/Vote/context/VoteController.tsx
  src/pages/Vote/context/VoteResultContext.tsx
  src/pages/Vote/context/tripInfo/TripInfoContext.tsx
  src/pages/Vote/context/tripInfo/TripInfoProvider.tsx
  src/pages/Vote/context/tripInfo/tripInfoSchema.ts
  src/pages/Vote/context/vote/VoteContext.tsx
  src/pages/Vote/context/vote/VoteProvider.tsx
  src/pages/Vote/context/vote/VoteResultSchema.ts
  src/pages/Vote/context/vote/VoteSchema.ts
  src/pages/Vote/context/voteResultSchema.ts
  src/pages/Vote/dummyData.ts
  src/pages/Vote/getResultTest.ts
  src/pages/Vote/test.ts
  src/react-query/mutation/vote/useVoteMutation.tsx
  src/react-query/queries/functionalQueries/useTripDetailQuery.ts
  src/react-query/queries/vote/useTripInfoQuery.tsx
  src/react-query/queries/vote/useVoteResultQuerie.ts
  src/store/useVoteRooomStore.ts
  src/store/useVoteStore.ts
  src/types/voteTypes/voteTypes.ts
Labels: 📬API, ✨Feature

#125 Feat/functional apis
  src/apis/functional/postVoteForm.ts
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/CalendarDays.tsx
  src/components/Calendar/CalendarHeader.tsx
  src/components/Calendar/CalendarTabs.tsx
  src/components/Calendar/CompleteButton.tsx
  src/components/Calendar/YearMonthPicker.tsx
  src/components/Calendar/context/CalendarContext.tsx
  src/components/Layout/FunctionalLayout.tsx
  src/components/Modal/ImageModal.tsx
  src/components/Modal/Modal.styles.ts
  src/hooks/useForm/useVoteForm.ts
  src/mocks/imageMock.ts
  src/mocks/tripDetailMock.ts
  src/mocks/tripPlanMock.ts
  src/pages/Functional/CreateCalendar/_components/CreateCalendar.tsx
  src/pages/Functional/CreateVote/_components/CreateVote.tsx
  src/pages/Functional/CreateVote/_components/SlideContainer/SlideContainer.tsx
  src/pages/Functional/CreateVote/_components/Tabs/Tabs.tsx
  src/pages/Functional/CreateVote/_components/VoteForm/Image.styles.ts
  src/pages/Functional/CreateVote/_components/VoteForm/ImagePlaceholder.tsx
  src/pages/Functional/CreateVote/_components/VoteForm/MessageInput.tsx
  src/pages/Functional/CreateVote/_components/VoteForm/VoteForm.tsx
  src/pages/Functional/CreateVote/_components/VoteForm/VoteTimes.tsx
  src/pages/Functional/CreateVote/_data/buttonData.ts
  src/pages/Functional/FunctionalPage.tsx
  src/pages/Functional/context/VoteFormContext.tsx
  src/pages/Functional/context/VoteFormProvider.tsx
  src/pages/Functional/schemas/VoteFormSchema.ts
  src/pages/Main/_components/FloatingButton/FloatingButton.tsx
  src/pages/SearchPage/_components/SearchListItem.tsx
  src/pages/SearchPage/index.tsx
  src/react-query/mutation/functional/useVoteFormMutation.ts
  src/store/useImageStore.ts
  src/types/functionalTypes/functionalTypes.ts
Labels: 📬API, ✨Feature

#149 Fix: Friend Page 라우트 연결 & 모달
  src/pages/MyPage/MyFriendPage/MyFriendPage.tsx
  src/pages/MyPage/MyFriendPage/_components/Friend/index.tsx
  src/pages/MyPage/MyFriendPage/_components/Room/index.tsx
Labels: 🐞Fix

#131 Feat : mainpage api 연결
  src/apis/Login/api.ts
  src/apis/friend/index.ts
  src/apis/main/TravelList/index.ts
  src/apis/main/TravelList/mocks.ts
  src/apis/main/Upcoming/index.ts
  src/apis/main/Upcoming/mocks.ts
  src/apis/main/Voting/index.ts
  src/apis/main/Voting/mocks.ts
  src/pages/Functional/FunctionalPage.tsx
  src/pages/Main/FullVotingListPage/FullVotingListPage.tsx
  src/pages/Main/_components/FloatingButton/FloatingButton.tsx
  src/pages/Main/_components/FloatingButton/Styles.ts
  src/pages/Main/_components/Main.Styles.ts
  src/pages/Main/_components/MainTravelHistory.tsx
  src/pages/Main/_components/MainUpcomingList.tsx
  src/pages/Main/_components/MainVotingList.tsx
  src/pages/Main/_components/TostModal/Styles.ts
  src/pages/Main/_components/TostModal/TostModal.tsx
  src/pages/Main/_components/TravelListItem/TravelListItem.tsx
  src/pages/Main/_components/UpcomingItem/UpcomingItem.tsx
  src/pages/Main/_components/VotingItem/FullVotingItem.tsx
  src/pages/Main/_components/VotingItem/VotingItem.Styles.ts
  src/pages/Main/_components/VotingItem/VotingItem.tsx
  src/pages/Main/_components/VotingItem/calculateRemainingTime.ts
  src/pages/Main/_components/VotingItem/useRemainingTimes.ts
  src/react-query/queries/main/TravelList/queries.ts
  src/react-query/queries/main/Upcoming/queries.ts
  src/react-query/queries/main/Voting/queries.ts
Labels: 📬API

#159 Feat: profile api연결
  src/apis/profile/index.ts
  src/pages/MyPage/MyProfilePage/MyProfilePage.tsx
  src/pages/MyPage/MyProfilePage/_components/ServiceSetting.tsx
  src/pages/MyPage/MyProfilePage/_components/Skeleton.tsx
  src/react-query/queries/profile/queries.ts
Labels: 📬API

#160 style : 예산 페이지 Skeleton UI
  src/pages/Budget/BudgetPage/BudgetPage.tsx
  src/pages/Budget/_components/CardSkeleton.tsx
Labels: 💄Design

#157 Style: 방 아이템 그룹 아바타 수정
  src/pages/MyPage/MyFriendPage/_components/ProfileGroup.tsx
Labels: 💄Design

#165 Style : mainpage 수정
  src/apis/main/Voting/index.ts
  src/pages/Main/FullVotingListPage/FullVotingListPage.tsx
  src/pages/Main/_components/CardSkeleton.tsx
  src/pages/Main/_components/Main.Styles.ts
  src/pages/Main/_components/MainTravelHistory.tsx
  src/pages/Main/_components/MainUpcomingList.tsx
  src/pages/Main/_components/MainVotingList.tsx
  src/pages/Main/_components/TostModal/Styles.ts
  src/pages/Main/_components/TravelListItem/TravelListItem.tsx
  src/pages/Main/_components/VotingItem/FullVotingItem.tsx
  src/pages/Main/_components/VotingItem/VotingItem.Styles.ts
  src/pages/Main/_components/VotingItem/VotingItem.tsx
Labels: 💄Design

#166 feat : user 이름 api 연결
  src/apis/user/index.ts
  src/apis/user/mocks.ts
  src/pages/Main/_components/MainTop.tsx
  src/react-query/queries/user/queries.ts
Labels: 📬API

#161 feat: button 컴포넌트 disabled 추가
  src/components/Button/Button.styles.ts
  src/components/Button/Button.tsx
  src/components/Button/types.ts
Labels: ✨Feature, 💄Design

#162 Fix: fuctional price calendar searchPage
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/CalendarDays.styles.ts
  src/components/Calendar/CalendarDays.tsx
  src/components/Calendar/CalendarHeader.tsx
  src/components/Calendar/CalendarTabs.styles.ts
  src/components/Calendar/CalendarTabs.tsx
  src/components/Calendar/CompleteButton.styles.ts
  src/components/Calendar/CompleteButton.tsx
  src/components/Calendar/MonthNavigation.tsx
  src/components/Calendar/YearMonthPicker.styles.ts
  src/components/Calendar/YearMonthPicker.tsx
  src/components/Calendar/YearSwiper/YearSwiper.tsx
  src/components/Calendar/context/CalendarContext.tsx
  src/hooks/useForm/useVoteForm.ts
  src/pages/Functional/CreateCalendar/_components/CreateCalendar.tsx
  src/pages/Functional/CreateVote/_components/CreateVote.tsx
  src/pages/Functional/CreateVote/_components/SlideContainer/SlideContainer.tsx
  src/pages/Functional/CreateVote/_components/Tabs/Tabs.tsx
  src/pages/Functional/CreateVote/_components/VoteForm/ImagePlaceholder.tsx
  src/pages/Functional/CreateVote/_components/VoteForm/MessageInput.tsx
  src/pages/Functional/CreateVote/_components/VoteForm/PriceInput.tsx
  src/pages/Functional/CreateVote/_components/VoteForm/Skeleton/SkeletonForm.tsx
  src/pages/Functional/CreateVote/_components/VoteForm/Skeleton/StyledSkeleton.ts
  src/pages/Functional/CreateVote/_components/VoteForm/VoteForm.tsx
  src/pages/Functional/CreateVote/_components/VoteForm/VoteTimes.tsx
  src/pages/Functional/FunctionalPage.tsx
  src/pages/SearchPage/_components/Pagination.tsx
  src/pages/SearchPage/_components/ResultList.tsx
  src/pages/SearchPage/_components/SearchListItem.tsx
  src/pages/SearchPage/_components/SearchMap/SearchMap.style.ts
  src/pages/SearchPage/_components/SearchMap/SearchMap.tsx
  src/pages/SearchPage/context/SearchContext.tsx
  src/pages/SearchPage/index.tsx
  src/pages/SearchPage/types/types.ts
Labels: 🐞Fix, ✨Feature, 💄Design, 🔨Refactor

#173 Feat: Course place 공유 페이
  src/assets/icons/Image.svg
  src/components/Card/CardImage.tsx
  src/components/Layout/CourseLayout.tsx
  src/hooks/useSetHeader.ts
  src/hooks/useShareForm.ts
  src/pages/Course/ShareCourse/Detail/index.tsx
  src/pages/Course/ShareCourse/List/_components/AddImage.tsx
  src/pages/Course/ShareCourse/List/_components/CourseSearchPage.tsx
  src/pages/Course/ShareCourse/List/_components/DeleteTitle.tsx
  src/pages/Course/ShareCourse/List/_components/ListCard.tsx
  src/pages/Course/ShareCourse/List/_components/Style.ts
  src/pages/Course/ShareCourse/List/index.tsx
  src/pages/Course/ShareCourse/Share/index.tsx
  src/pages/Course/ShareCourse/ShareCorsePage.tsx
  src/pages/Course/ShareCourse/schema.ts
  src/pages/Course/_components/Course.style.ts
  src/pages/Course/constants.ts
  src/pages/SearchPage/_components/SearchListItem.tsx
  src/pages/SearchPage/index.tsx
  src/types/header/header.ts
Labels: ✨Feature, 💄Design

#175 Fix/fuctional
  src/pages/Functional/CreateVote/_components/VoteForm/VoteForm.tsx
  src/pages/Functional/FunctionalPage.tsx
  src/pages/Functional/context/SearchContext.tsx
Labels: 🐞Fix, ✨Feature, 💄Design

#178 Feat: Course 장소 공유 API 연결
  src/App.tsx
  src/Utils/useLongPress.ts
  src/apis/Login/api.ts
  src/apis/course/index.ts
  src/apis/course/mocks.ts
  src/apis/course/types.ts
  src/components/Layout/CourseLayout.tsx
  src/pages/Course/CoursePage.tsx
  src/pages/Course/ShareCourse/Detail/_components/DetailCard.tsx
  src/pages/Course/ShareCourse/Detail/index.tsx
  src/pages/Course/ShareCourse/List/_components/ButtonLoading.tsx
  src/pages/Course/ShareCourse/List/_components/ListCard.tsx
  src/pages/Course/ShareCourse/List/index.tsx
  src/pages/Course/ShareCourse/Share/_components/ChatInterface.tsx
  src/pages/Course/ShareCourse/Share/_components/ChatMessage.tsx
  src/pages/Course/ShareCourse/Share/_components/InfoToggle.tsx
  src/pages/Course/ShareCourse/Share/_components/ShareSkeleton.tsx
  src/pages/Course/ShareCourse/Share/index.tsx
  src/pages/Course/ShareCourse/ShareCorsePage.tsx
  src/pages/Course/ShareCourse/schema.ts
  src/pages/Course/SharedCourse/Detail/index.tsx
  src/pages/Course/SharedCourse/SharedCoursePage.tsx
  src/pages/Course/constants.ts
  src/pages/MyPage/MyFriendPage/_components/FriendItem.tsx
  src/react-query/mutation/course/mutations.ts
  src/react-query/mutation/friend/mutations.ts
  src/react-query/queries/course/queries.ts
  src/react-query/queries/friend/queries.ts
Labels: ✨Feature

#179 Fix: build error 해결
  src/apis/course/mocks.ts
  src/hooks/useResultSelection.ts
  src/react-query/queries/functionalQueries/useTripDetailQuery.ts
Labels: 🌏Deploy

#180 Fix: api error 처리
  src/apis/course/index.ts
  src/apis/friend/index.ts
  src/apis/main/TravelList/index.ts
  src/apis/main/Upcoming/index.ts
  src/apis/main/Voting/index.ts
  src/apis/notice/index.ts
  src/apis/room/index.ts
  src/apis/user/index.ts
  src/apis/vote/tripInfo.ts
  src/apis/vote/vote.ts
  src/apis/vote/voteResult.ts
Labels: 📬API, 🌏Deploy

#169 Feat : mainpage api형식 변경 수정, notice api연결
  git
  src/apis/main/TravelList/mocks.ts
  src/apis/main/Upcoming/mocks.ts
  src/apis/main/Voting/mocks.ts
  src/apis/main/notice/index.ts
  src/apis/main/notice/mocks.ts
  src/apis/user/mocks.ts
  src/pages/Main/FullVotingListPage/FullVotingListPage.tsx
  src/pages/Main/_components/CardSkeleton.tsx
  src/pages/Main/_components/MainTop.tsx
  src/pages/Main/_components/MainTravelHistory.tsx
  src/pages/Main/_components/MainUpcomingList.tsx
  src/pages/Main/_components/MainVotingList.tsx
  src/pages/Main/_components/TravelListItem/TravelListItem.tsx
  src/pages/Main/_components/UpcomingItem/UpcomingItem.tsx
  src/pages/Main/_components/VotingItem/FullVotingItem.tsx
  src/pages/Main/_components/VotingItem/VotingItem.Styles.ts
  src/pages/Main/_components/VotingItem/VotingItem.tsx
  src/pages/Main/_components/VotingItem/useRemainingTimes.ts
  src/react-query/queries/main/notice/queries.ts
Labels: 🐞Fix, 📬API, ✨Feature, 💄Design, 🔨Refactor

#181 fix/navigate-room
  src/pages/Functional/CreateVote/_components/SlideContainer/SlideContainer.tsx
  src/pages/SearchPage/_components/SearchMap/SearchMap.style.ts
  src/pages/SearchPage/_components/SearchMap/SearchMap.tsx
Labels: 🐞Fix

#184 Fix:mainpage
  src/apis/main/Voting/mocks.ts
  src/pages/Main/FullVotingListPage/FullVotingListPage.tsx
  src/pages/Main/_components/MainTravelHistory.tsx
  src/pages/Main/_components/MainUpcomingList.tsx
  src/pages/Main/_components/MainVotingList.tsx
  src/pages/Main/_components/VotingItem/FullVotingItem.tsx
  src/pages/Main/_components/VotingItem/VotingItem.Styles.ts
  src/pages/Main/_components/VotingItem/VotingItem.tsx
  src/pages/SearchPage/_components/SearchMap/SearchMap.style.ts
  src/pages/SearchPage/_components/SearchMap/SearchMap.tsx
Labels: 🐞Fix

#177 Style:onboarding
  src/App.tsx
  src/assets/icons/onboarding1.svg
  src/assets/icons/onboarding2.svg
  src/assets/icons/onboarding3.svg
  src/pages/Functional/CreateVote/_components/VoteForm/VoteForm.tsx
  src/pages/Splash/SplashPage/SplashPage.tsx
  src/pages/Splash/onboardingPage/Styles.ts
  src/pages/Splash/onboardingPage/onboardingPagePage.tsx
Labels: 💄Design

#185 Fix/vote state
  src/pages/Vote/ConfirmPage/ConfirmSuccessPage/ConfirmSuccessPage.tsx
  src/pages/Vote/Travel/_components/SkeletonStyles.ts
  src/pages/Vote/Travel/_components/SkeletonTravelCard.tsx
  src/pages/Vote/Travel/_components/TravelCard.tsx
  src/pages/Vote/VoteCard/_components/SkeletonVoteCard.tsx
  src/pages/Vote/VoteCard/_components/VoteCard.tsx
  src/pages/Vote/VoteResult/_components/ResultCard.tsx
  src/pages/Vote/VoteResult/_components/SkeletonResult/SkeletonResult.tsx
  src/pages/Vote/_components/Vote.styles.ts
  src/pages/Vote/context/VoteResultContext.tsx
Labels: 🐞Fix, ✨Feature, 💄Design

#187 fix:메인페이지 진행중 카드 라우팅
  src/pages/Main/_components/VotingItem/FullVotingItem.tsx
  src/pages/Main/_components/VotingItem/VotingItem.tsx
Labels: 🐞Fix

#200 Fix: searchInput-color
  src/components/Input/Input.style.ts
Labels: 🐞Fix, 💄Design

#202 Feat: budget api style
  src/apis/budget/index.ts
  src/apis/budget/mocks.ts
  src/apis/budget/types.ts
  src/pages/Budget/_components/CardSkeleton.tsx
  src/react-query/mutation/budget/budgetMutation.tsx
Labels: 🐞Fix, 💄Design

#206 Fix: login 로직 수정
  src/apis/Login/api.ts
  src/pages/Login/Kakao.tsx
  src/pages/Login/useAuthStore.ts
  src/pages/Main/_components/MainTop.tsx
  src/pages/MyPage/MyProfilePage/MyProfilePage.tsx
  src/pages/MyPage/MyProfilePage/_components/Skeleton.tsx
  src/pages/MyPage/MyProfilePage/_components/UserProfile.tsx
Labels: 🐞Fix, 📬API

#208 Fix: vote api
  src/App.tsx
  src/apis/functional/roomList/index.ts
  src/apis/functional/roomList/types.ts
  src/apis/searchAddress/index.ts
  src/apis/vote/mocks/tripInfoMocks.ts
  src/apis/vote/mocks/voteResultMocks.ts
  src/apis/vote/tripInfo.ts
  src/apis/vote/voteResult.ts
  src/apis/vote/voteResultPost.ts
  src/assets/icons/building1.svg
  src/assets/icons/building2.svg
  src/assets/icons/building3.svg
  src/assets/icons/building4.svg
  src/assets/icons/nature1.svg
  src/assets/icons/nature2.svg
  src/assets/icons/nature3.svg
  src/assets/icons/nature4.svg
  src/pages/Functional/CreateVote/_components/SlideContainer/SlideContainer.tsx
  src/pages/Functional/CreateVote/_components/SlideContainer/Styles.ts
  src/pages/Vote/Travel/_components/TravelCard.tsx
  src/pages/Vote/VoteCard/_components/VoteCard.tsx
  src/pages/Vote/VotePage.tsx
  src/pages/Vote/VoteResult/_components/DurationInfo.tsx
  src/pages/Vote/VoteResult/_components/ResultCard.tsx
  src/pages/Vote/VoteResult/_components/VoteComponent.tsx
  src/pages/Vote/VoteResult/_components/VoteResult.tsx
  src/pages/Vote/context/VoteController.tsx
  src/pages/Vote/context/VoteResultContext.tsx
  src/pages/Vote/context/tripInfo/TripInfoContext.tsx
  src/pages/Vote/context/tripInfo/TripInfoProvider.tsx
  src/pages/Vote/context/tripInfo/tripInfoSchema.ts
  src/pages/Vote/context/voteResultSchema.ts
  src/react-query/mutation/vote/useVoteMutation.tsx
  src/react-query/queries/functional/roomListQuery.ts
  src/react-query/queries/vote/useTripInfoQuery.tsx
  src/react-query/queries/vote/useVoteResultQuerie.ts
Labels: 🐞Fix, 📬API, ✨Feature

#215 Fix: Room API 변경 -> Axios 객체로 리팩토링
  src/apis/Axios.ts
  src/apis/Login/api.ts
  src/apis/budget/index.ts
  src/apis/course/index.ts
  src/apis/friend/index.ts
  src/apis/functional/postVoteForm.ts
  src/apis/main/TravelList/index.ts
  src/apis/main/Upcoming/index.ts
  src/apis/main/Voting/index.ts
  src/apis/main/notice/index.ts
  src/apis/notice/index.ts
  src/apis/profile/index.ts
  src/apis/room/index.ts
  src/apis/upcomingCourse/index.ts
  src/apis/user/index.ts
  src/apis/vote/tripInfo.ts
  src/apis/vote/vote.ts
  src/apis/vote/voteResult.ts
Labels: 📬API

#217 Style:mainpage empty 박스
  src/apis/main/TravelList/mocks.ts
  src/apis/main/Upcoming/mocks.ts
  src/apis/main/Voting/mocks.ts
  src/pages/Main/_components/Main.Styles.ts
  src/pages/Main/_components/TravelListItem/TravelListItem.Styles.ts
  src/pages/Main/_components/UpcomingItem/UpcomingItem.Styles.ts
  src/pages/Main/_components/VotingItem/VotingItem.Styles.ts
Labels: 💄Design

#213 Fix : mainpage 리렌더링, 플로팅 버튼, fulllist 라우팅 설정
  src/apis/main/TravelList/mocks.ts
  src/apis/main/Upcoming/mocks.ts
  src/apis/main/Voting/mocks.ts
  src/pages/Main/_components/FloatingButton/FloatingButton.tsx
  src/pages/Main/_components/FloatingButton/Styles.ts
  src/pages/Main/_components/MainTop.tsx
  src/pages/Main/_components/VotingItem/FullVotingItem.tsx
  src/pages/Main/_components/VotingItem/VotingItem.tsx
  src/pages/Main/_components/VotingItem/useRemainingTimes.ts
  src/pages/Main/_components/VotingItem/useRemainingTimes.tsx
Labels: 🐞Fix

#218 Feat: 인증 인가 hoc 컴포넌트 수정 & 사용하지 않는 페이지 삭제
  src/App.tsx
  src/apis/course/index.ts
  src/apis/user/index.ts
  src/apis/user/mocks.ts
  src/components/Layout/BudgetLayout.tsx
  src/components/Layout/CourseLayout.tsx
  src/components/Layout/FullVotingListLayout.tsx
  src/components/Layout/FunctionalLayout.tsx
  src/components/Layout/NoticeLayout.tsx
  src/components/Layout/ProfileLayout.tsx
  src/components/Layout/VoteLayout.tsx
  src/components/Modal/Modal.styles.ts
  src/components/Modal/core.tsx
  src/pages/Course/ShareCourse/List/index.tsx
  src/pages/Course/ShareCourse/ShareCorsePage.tsx
  src/pages/Login/Kakao.tsx
  src/pages/Login/useAuthStore.ts
  src/pages/Login/withAuth.tsx
  src/pages/MyPage/MyFriendPage/MyFriendPage.tsx
  src/pages/MyPage/MyProfilePage/MyProfilePage.tsx
  src/pages/Scheduling/BudgetSelectPage/BudgetSelectPage.tsx
  src/pages/Scheduling/BudgetSelectPage/Styles.ts
  src/pages/Scheduling/DateSelectPage/DateSelectPage.tsx
  src/pages/Scheduling/DateSelectPage/Styles.ts
  src/pages/Scheduling/SchedulePage/SchedulePage.tsx
  src/pages/Scheduling/SchedulePage/Styles.ts
Labels: 📬API

#221 Fix: 빌드 에러 임시 해결
  src/apis/user/index.ts
  src/hooks/useShareForm.ts
  src/pages/Course/constants.ts
  src/pages/Vote/ConfirmPage/ConfirmSuccessPage/ConfirmSuccessPage.tsx
  src/pages/Vote/context/vote/VoteProvider.tsx
  src/react-query/queries/vote/useTripInfoQuery.tsx
Labels: 🌏Deploy

#222 feat: modal 버튼 하나만 보일 수 있게 옵션 추가
  src/components/Modal/core.tsx
  src/components/Modal/index.ts
  src/store/modal/index.ts
Labels: ✨Feature

#224 Fix: 친구 & 방 생성 페이지
  src/App.tsx
  src/apis/friend/index.ts
  src/apis/friend/types.ts
  src/apis/room/index.ts
  src/apis/room/types.ts
  src/pages/MyPage/InvitePage/InvitePage.tsx
  src/pages/MyPage/InvitePage/_components/Invite.styles.ts
  src/pages/MyPage/InvitePage/_components/LoadingText.tsx
  src/pages/MyPage/MyFriendPage/_components/Accordion.tsx
  src/pages/MyPage/MyFriendPage/_components/Friend/index.tsx
  src/pages/MyPage/MyFriendPage/_components/FriendItem.tsx
  src/pages/MyPage/RoomPage/RoomPageContent.tsx
  src/react-query/mutation/friend/mutations.ts
  src/react-query/queries/friend/queries.ts
  src/react-query/queries/room/queries.ts
Labels: 📬API

#226 fix: api 주소 잘못됨
  src/apis/main/Upcoming/index.ts
Labels: 📬API

#227 Feat:mainpage 투표완료 추가
  src/apis/main/TravelList/index.ts
  src/apis/main/TravelList/types.ts
  src/apis/main/Upcoming/index.ts
  src/apis/main/Upcoming/types.ts
  src/apis/main/Voting/index.ts
  src/apis/main/Voting/mocks.ts
  src/apis/main/Voting/types.ts
  src/apis/main/notice/index.ts
  src/apis/main/notice/mocks.ts
  src/apis/main/notice/types.ts
  src/pages/Main/FullVotingListPage/FullVotingListPage.tsx
  src/pages/Main/_components/MainTop.tsx
  src/pages/Main/_components/MainTravelHistory.tsx
  src/pages/Main/_components/MainVotingList.tsx
  src/pages/Main/_components/TravelListItem/TravelListItem.tsx
  src/pages/Main/_components/UpcomingItem/UpcomingItem.tsx
  src/pages/Main/_components/VotingItem/FullVotingItem.tsx
  src/pages/Main/_components/VotingItem/VotingItem.tsx
  src/pages/Main/_components/utils.ts
Labels: ✨Feature, 💄Design

#228 Feat: AI Course Page
  src/Utils/AiCourseToKaKaoCourse.ts
  src/apis/course/index.ts
  src/apis/course/mocks.ts
  src/apis/course/types.ts
  src/pages/Course/CoursePage.tsx
  src/pages/Course/SharedCourse/Detail/_components/CourseDayButton.tsx
  src/pages/Course/SharedCourse/Detail/_components/CourseDetailCard.tsx
  src/pages/Course/SharedCourse/Detail/_components/CourseDetailCarousel.tsx
  src/pages/Course/SharedCourse/Detail/index.tsx
  src/pages/Course/SharedCourse/Overview/index.tsx
  src/pages/Course/SharedCourse/SharedCoursePage.tsx
  src/react-query/mutation/course/mutations.ts
  src/react-query/queries/course/queries.ts
Labels: 📬API, ✨Feature

#232 Fix: 로그아웃, 탈퇴 API 연결
  src/apis/profile/index.ts
  src/pages/MyPage/MyProfilePage/MyProfilePage.tsx
  src/pages/MyPage/MyProfilePage/_components/ServiceSetting.tsx
  src/react-query/mutation/profile/mutations.ts
Labels: 📬API

#223 Fix/vote state
  src/apis/functional/postVoteForm.ts
  src/apis/functional/types.ts
  src/apis/vote/tripInfo.ts
  src/apis/vote/vote.ts
  src/apis/vote/voteResult.ts
  src/apis/vote/voteResultPost.ts
  src/components/Calendar/context/CalendarContext.tsx
  src/hooks/useForm/useVoteForm.ts
  src/hooks/useTripInfo.ts
  src/pages/Functional/CreateVote/_components/CreateVote.tsx
  src/pages/Functional/CreateVote/_components/SlideContainer/SlideContainer.tsx
  src/pages/Functional/CreateVote/_components/SlideContainer/Styles.ts
  src/pages/Functional/CreateVote/_components/VoteForm/Image.styles.ts
  src/pages/Functional/CreateVote/_components/VoteForm/ImagePlaceholder.tsx
  src/pages/Functional/CreateVote/_components/VoteForm/Message.styles.ts
  src/pages/Functional/CreateVote/_components/VoteForm/MessageInput.tsx
  src/pages/Functional/CreateVote/_components/VoteForm/PriceInput.tsx
  src/pages/Functional/CreateVote/_components/VoteForm/VoteForm.tsx
  src/pages/Functional/CreateVote/_components/VoteForm/VoteTimes.tsx
  src/pages/Functional/_components/Functional.styles.ts
  src/pages/Functional/context/VoteFormContext.tsx
  src/pages/Functional/schemas/VoteFormSchema.ts
  src/pages/Vote/ConfirmPage/ConfirmFailPage/ConfirmFailPage.tsx
  src/pages/Vote/ConfirmPage/ConfirmSuccessPage/ConfirmSuccessPage.tsx
  src/pages/Vote/Travel/_components/TravelCard.tsx
  src/pages/Vote/VoteCard/_components/VoteButton.tsx
  src/pages/Vote/VoteCard/_components/VoteCard.tsx
  src/pages/Vote/VotePage.tsx
  src/pages/Vote/VoteResult/_components/DurationInfo.tsx
  src/pages/Vote/VoteResult/_components/ResultCard.tsx
  src/pages/Vote/VoteResult/_components/VoteComponent.tsx
  src/pages/Vote/VoteResult/_components/VoteResult.tsx
  src/pages/Vote/_components/Vote.styles.ts
  src/pages/Vote/context/VoteResultContext.tsx
  src/pages/Vote/context/tripInfo/TripInfoContext.tsx
  src/pages/Vote/context/tripInfo/TripInfoProvider.tsx
  src/pages/Vote/context/tripInfo/tripInfoSchema.ts
  src/pages/Vote/context/vote/VoteContext.tsx
  src/pages/Vote/context/vote/VoteDataType.ts
  src/pages/Vote/context/vote/VoteProvider.tsx
  src/pages/Vote/context/vote/VoteResultSchema.ts
  src/pages/Vote/context/vote/VoteResultTypes.ts
  src/pages/Vote/context/vote/VoteSchema.ts
  src/pages/Vote/context/voteResultSchema.ts
  src/react-query/mutation/functional/useVoteFormMutation.ts
  src/react-query/mutation/vote/useVoteMainMutation.tsx
  src/react-query/mutation/vote/useVoteMutation.tsx
  src/react-query/queries/vote/useTripInfoQuery.tsx
  src/react-query/queries/vote/useVoteResultQuerie.ts
  src/types/voteTypes/voteTypes.ts
Labels: 🐞Fix, 📬API, 🔨Refactor

#235 Fix: Course 단일 장소에 대한 카드 처리 & 마크 디자인 변경
  public/Icon192.png
  public/icon192.png
  public/icon512.png
  src/App.tsx
  src/Utils/AiCourseToKaKaoCourse.ts
  src/apis/budget/index.ts
  src/apis/budget/types.ts
  src/components/Layout/BudgetLayout.tsx
  src/components/Layout/FunctionalLayout.tsx
  src/components/Layout/NoticeLayout.tsx
  src/components/Layout/ProfileLayout.tsx
  src/components/Layout/VoteLayout.tsx
  src/components/Map/index.tsx
  src/pages/Budget/BudgetPage/BudgetPage.tsx
  src/pages/Budget/_components/BudgetCard.tsx
  src/pages/Budget/_components/BudgetInfoCard.tsx
  src/pages/Budget/_components/BudgetSkeleton.tsx
  src/pages/Budget/_components/Styles.ts
  src/pages/Course/_components/CoursePlaces.tsx
  src/react-query/queries/budget/budgetQuery.tsx
Labels: 🐞Fix

#225 Feat:upcomingcourse
  src/App.tsx
  src/apis/main/TravelList/mocks.ts
  src/apis/main/Upcoming/index.ts
  src/apis/main/Upcoming/mocks.ts
  src/apis/main/Voting/mocks.ts
  src/apis/upcomingCourse/index.ts
  src/apis/upcomingCourse/mocks.ts
  src/apis/upcomingCourse/types.ts
  src/pages/Course/UpComingCourse/UpComingCoursePage.tsx
  src/pages/Course/UpComingCourse/_components/RecommendCard.tsx
  src/pages/Course/UpComingCourse/_components/UpComingCourse.style.ts
  src/pages/Course/UpComingCourse/_components/UpComingCourseCard.tsx
  src/react-query/queries/queries.ts
  src/react-query/queries/upcomingCourse/queries.ts
Labels: 🐞Fix, ✨Feature, 💄Design

#238 Feat: Budget 예산 페이지 렌더링
  src/apis/budget/types.ts
  src/pages/Budget/BudgetPage/BudgetPage.tsx
  src/pages/Budget/_components/BudgetCard.tsx
  src/pages/Budget/_components/BudgetInfoCard.tsx
  src/pages/Budget/_components/getBudgetType.ts
Labels: 📬API

#242 Chore: api 수정 및 시간 수정
  src/apis/course/index.ts
  src/apis/course/types.ts
  src/apis/main/TravelList/index.ts
  src/apis/main/Upcoming/index.ts
  src/apis/main/Voting/index.ts
  src/pages/Main/_components/VotingItem/useRemainingTimes.tsx
  src/pages/Main/_components/utils.ts
  src/react-query/mutation/course/mutations.ts
Labels: 🐞Fix, 📬API

#243 Feat:mainpage 목업데이터
  src/apis/main/TravelList/index.ts
  src/apis/main/TravelList/mocks.ts
  src/apis/main/Upcoming/mocks.ts
  src/apis/main/Voting/mocks.ts
Labels: 💄Design

#245 fix:로그아웃시 라우팅 처리
  src/react-query/mutation/profile/mutations.ts
Labels: 🐞Fix

#248 Fix: main notice api 수정 & query 캐싱 option 추가 & budget api 수정
  src/apis/budget/index.ts
  src/apis/budget/types.ts
  src/apis/main/notice/index.ts
  src/apis/notice/index.ts
  src/hooks/useNotice.ts
  src/pages/Budget/_components/BudgetCard.tsx
  src/pages/Main/_components/MainTop.tsx
  src/react-query/queries/main/TravelList/queries.ts
  src/react-query/queries/main/Upcoming/queries.ts
  src/react-query/queries/main/Voting/queries.ts
  src/react-query/queries/main/notice/queries.ts
Labels: 🐞Fix, 📬API, 🔨Refactor

#247 Fix: vote chore
  src/pages/Vote/VoteCard/_components/VoteButton.tsx
  src/pages/Vote/VoteResult/_components/ResultCard.tsx
  src/pages/Vote/VoteResult/_components/VoteResult.tsx
Labels: 🐞Fix

#249 fix: 예산 mockData 타입 수정
  src/apis/budget/mocks.ts
Labels: 🌏Deploy

#253 feat:여행 타입 라우터
  src/apis/main/Upcoming/mocks.ts
  src/apis/main/Upcoming/types.ts
  src/pages/Main/_components/FloatingButton/Styles.ts
  src/pages/Main/_components/UpcomingItem/UpcomingItem.tsx
Labels: 🐞Fix

#251 fix: default image 추가
  src/apis/room/types.ts
  src/pages/MyPage/MyFriendPage/_components/ProfileGroup.tsx
Labels: 💄Design

#256 fix/vote-state/count
  src/apis/functional/roomList/types.ts
  src/pages/Vote/ConfirmPage/ConfirmSuccessPage/ConfirmSuccessPage.tsx
  src/pages/Vote/ConfirmPage/_components/Recommend/Recommend.tsx
  src/pages/Vote/Travel/_components/TravelCard.tsx
  src/pages/Vote/VoteCard/_components/VoteCard.tsx
  src/pages/Vote/VoteResult/_components/ResultCard.tsx
  src/pages/Vote/VoteResult/_components/VoteComponent.tsx
Labels: 🐞Fix, 📬API

#258 Feat:mainpage
  src/pages/Main/_components/UpcomingItem/UpcomingItem.tsx
  src/pages/Main/_components/VotingItem/FullVotingItem.tsx
Labels: 🐞Fix

#262 Fix: Vote Header, Functional Profile
  src/pages/Functional/CreateVote/_components/SlideContainer/SlideContainer.tsx
  src/pages/Functional/CreateVote/_components/SlideContainer/Styles.ts
  src/pages/Vote/Travel/_components/TravelCard.tsx
  src/pages/Vote/VoteCard/_components/VoteCard.tsx
  src/pages/Vote/VoteResult/_components/VoteResult.tsx
  src/pages/Vote/context/tripInfo/TripInfoProvider.tsx
Labels: 🐞Fix, 💄Design
